CONFIG_NAME: 'minimal'

TERMINAL_TOTAL_DIFFICULTY: 2 # Has to match geth-genesis

ALTAIR_FORK_EPOCH: 1
BELLATRIX_FORK_EPOCH: 2
CAPELLA_FORK_EPOCH: 3
EIP4844_FORK_EPOCH: 4

SECONDS_PER_SLOT: 6
# SLOTS_PER_EPOCH: 3 -- this is not configurable in Lodestar
