version: '3.4'

volumes:
  geth_data:
  geth_data2:
  nethermind_data:
  nethermind_data_2:
  beacon_node_data:
  beacon_node_follower_data:
  lighthouse_shared_config:
  lighthouse_data:
  beacon_node_follower_data_2:
  lodestar_beacon_node_follower_data_2:

services:
  execution-bootnode:
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    command: /usr/local/bin/bootnode.sh
    volumes:
      - type: bind
        source: ./geth/bootnode.sh
        target: /usr/local/bin/bootnode.sh
 
  execution-node:
    depends_on:
      #- execution-bootnode
      - lcli-build-genesis
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8545:8545'
    entrypoint: ["geth.sh"]
    volumes:
      - 'geth_data:/db'
      - lighthouse_shared_config:/shared-configs
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  execution-node-2:
    depends_on:
      - execution-node
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8546:8545'
    entrypoint: ["geth.sh"]
    volumes:
      - 'geth_data2:/db'
      - lighthouse_shared_config:/shared-configs
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  nethermind-execution-node:
    depends_on:
      - execution-node
    build:
      context: ./nethermind
      dockerfile: ./Dockerfile.nethermind
    ports:
      - "8547:8545"
    volumes:
      - "nethermind_data:/db"
      - "./nethermind/genesis.json:/genesis.json"
      - "./nethermind/config.cfg:/nethermind/configs/mainnet.cfg"

  nethermind-execution-node-2:
    depends_on:
      - execution-node
    build:
      context: ./nethermind
      dockerfile: ./Dockerfile.nethermind
    ports:
      - "8548:8545"
    volumes:
      - "nethermind_data_2:/db"
      - "./nethermind/genesis.json:/genesis.json"
      - "./nethermind/config.cfg:/nethermind/configs/mainnet.cfg"

  prysm-beacon-node:
    depends_on:
      - execution-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint:
      ['run_beacon_node.sh', '--min-sync-peers=0', '--bootstrap-node=']
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/prysm-priv-key
        target: /etc/prysm-priv-key

  prysm-beacon-node-follower:
    depends_on:
      - execution-node-2
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node-follower
      BEACON_NODE_RPC: http://prysm-beacon-node:3500
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./prysm/prysm-follower-priv-key
        target: /etc/prysm-priv-key

  prysm-beacon-node-follower-2:
    depends_on:
      - nethermind-execution-node
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://nethermind-execution-node:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node-follower-2
      BEACON_NODE_RPC: http://prysm-beacon-node:3500
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3502:3500'
      - '4002:4000'
      - '13002:13000'
    volumes:
      - 'beacon_node_follower_data_2:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./prysm/prysm-follower-priv-key
        target: /etc/prysm-priv-key

  prysm-validator-node:
    depends_on:
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --interop-num-validators=4
      --interop-start-index=0
      --force-clear-db
      --chain-config-file=/config/chain-config.yml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml

  lodestar-beacon-node:
    depends_on:
      - execution-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      PROCESS_NAME: lodestar-beacon-node
    entrypoint: ['run_beacon_node.sh']
    ports:
      - '3500:3500'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh

  lodestar-beacon-node-follower:
    depends_on:
      - execution-node-2
      - lodestar-beacon-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      BEACON_NODE_RPC: http://lodestar-beacon-node:3500
      PROCESS_NAME: lodestar-beacon-node-follower
      VERBOSITY: debug
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lodestar/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh

  lodestar-beacon-node-follower-2:
    depends_on:
      - nethermind-execution-node-2
      - prysm-beacon-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://nethermind-execution-node-2:8545
      BEACON_NODE_RPC: http://prysm-beacon-node:3500
      PROCESS_NAME: lodestar-beacon-node-follower-2
      VERBOSITY: debug
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3505:3500'
      - '13005:13000'
    volumes:
      - 'lodestar_beacon_node_follower_data_2:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lodestar/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh

  # TODO: temporary solution for generating genesis, remove this before merge
  lcli-build-genesis:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    entrypoint: ["generate-genesis.sh"]
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - "./lighthouse/vars.env:/config/vars.env"
      - type: bind
        source: ./lighthouse/generate-genesis.sh
        target: /usr/local/bin/generate-genesis.sh
      - type: bind
        source: ./lighthouse/genesis.json
        target: /config/genesis.json
      - type: bind
        source: ./lighthouse/generated-genesis.json
        target: /config/generated-genesis.json
      - type: bind
        source: ./lighthouse/generated-config.yaml
        target: /config/generated-config.yaml

  lighthouse-bootnode:
    depends_on:
      - lcli-build-genesis
    image: lighthouse-interop
    pull_policy: never
    command: run_bootnode.sh
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_bootnode.sh
        target: /usr/local/bin/run_bootnode.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
 
  lighthouse-beacon-node:
    depends_on:
      - lighthouse-bootnode
      - execution-node
      - lcli-build-genesis
    # build:
    #   context: ./lighthouse
    #   dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_1", "http://execution-node:8551"]
    environment:
      - P2P_PORT=9000
    ports:
      - "5052:5052"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret

  lighthouse-beacon-node-follower:
    depends_on:
      - execution-node-2
      - lighthouse-beacon-node
    # build:
    #   context: ./lighthouse
    #   dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_2", "http://execution-node-2:8551"]
    environment:
      - P2P_PORT=9001
    ports:
      - "5053:5052"
      - "8001:8000"
      - "9001:9001"
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret

  lighthouse-validator-node:
    image: lighthouse-interop
    pull_policy: never
    depends_on:
      - lighthouse-beacon-node
    entrypoint: ['run_validator.sh', 'http://lighthouse-beacon-node:8000']
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_validator.sh
        target: /usr/local/bin/run_validator.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
 
  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
