version: '3.4'

volumes:
  beacon_node_data:
  beacon_node_follower_data:
  lighthouse_data:
  prysm_data:
  lodestar_data:
  config_data:

services:
  genesis-generator:
    image: inphi/ethereum-genesis-generator:eip4844-alpha
    entrypoint: run_genesis_generator.sh
    volumes:
      - ./shared/run_genesis_generator.sh:/usr/local/bin/run_genesis_generator.sh
      - ./shared/genesis-generator-configs:/config
      - ./shared/generated-configs:/gen-configs
      - lighthouse_data:/lighthouse_data
      - prysm_data:/prysm_data
      - lodestar_data:/lodestar_data
      - config_data:/data

  execution-node:
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8545:8545'
      - '8551:8551'
    entrypoint: ["geth.sh"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8545"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 1s
    volumes:
      - 'config_data:/config_data'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  execution-node-2:
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8545"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 1s
    ports:
      - '8546:8545'
      - '8552:8551'
    entrypoint: ["geth.sh"]
    volumes:
      - 'config_data:/config_data'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  execution-node-3:
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8545"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 1s
    ports:
      - '8547:8545'
      - '8553:8551'
    entrypoint: ["geth.sh"]
    volumes:
      - 'config_data:/config_data'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  nethermind:
    image: nethermindeth/nethermind:eip-4844-v4
    ports:
      - '10545:8545'
    entrypoint: 'nethermind.sh'
    volumes:
      - 'config_data:/config_data'
      - type: bind
        source: ./nethermind/nethermind.sh
        target: /usr/local/bin/nethermind.sh

  # TODO: move bootnode to genesis-generator
  bootnode:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    pull_policy: never
    command: run_bootnode.sh
    volumes:
      - lighthouse_data:/data
      - config_data:/config_data
      - ./shared/genesis-generator-configs/values.env:/config/values.env
      - type: bind
        source: ./lighthouse/run_bootnode.sh
        target: /usr/local/bin/run_bootnode.sh

  prysm-beacon-node:
    depends_on:
      nethermind:
        condition: service_started
      #execution-node:
      #condition: service_healthy
      bootnode:
        condition: service_started
      jaeger-tracing:
        condition: service_started
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:3500/eth/v1/node/health"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 1s
    environment:
      EXECUTION_NODE_URL: http://nethermind:8551
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
      P2P_TCP_PORT: 13000
      MIN_SYNC_PEERS: 0
    entrypoint: run_beacon_node.sh
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - 'config_data:/config_data'
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/prysm-priv-key
        target: /etc/prysm-priv-key

  prysm-beacon-node-follower:
    depends_on:
      execution-node-2:
        condition: service_healthy
      prysm-beacon-node:
        condition: service_started
      bootnode:
        condition: service_started
      jaeger-tracing:
        condition: service_started
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8551
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node-follower
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
      P2P_TCP_PORT: 13001
      MIN_SYNC_PEERS: 1
    entrypoint: run_beacon_node.sh
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13001'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - 'config_data:/config_data'
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/prysm-follower-priv-key
        target: /etc/prysm-priv-key

  prysm-validator-node:
    depends_on:
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --force-clear-db
      --chain-config-file=/config_data/custom_config_data/config.yaml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --wallet-password-file=/prysm_data/wallet_pass.txt
      --wallet-dir=/prysm_data/wallet
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - 'config_data:/config_data'
      - 'prysm_data:/prysm_data'

  lodestar-beacon-node:
    depends_on:
      bootnode:
        condition: service_started
      execution-node-3:
        condition: service_healthy
    image: g11tech/lodestar:4844-jan23
    environment:
      EXECUTION_NODE_URL: http://execution-node-3:8551
    entrypoint: ['run_beacon_node.sh']
    ports:
      - '3600:3500'
      - '14000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - 'config_data:/config_data'
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh

  lodestar-validator-node:
    depends_on:
      - lodestar-beacon-node
    image: g11tech/lodestar:4844-jan23
    command: >
      node ./packages/cli/bin/lodestar validator
      --paramsFile /config_data/custom_config_data/config.yaml
      --force
      --dataDir /chaindata/validator
      --keystoresDir /lodestar_data/keystores
      --secretsDir /lodestar_data/secrets
      --server http://lodestar-beacon-node:3500
      --suggestedFeeRecipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
    volumes:
      - 'beacon_node_data:/chaindata'
      - 'config_data:/config_data'
      - 'lodestar_data:/lodestar_data'
      - type: bind
        source: ./lodestar/run_validator.sh
        target: /usr/local/bin/run_validator.sh

  lighthouse-beacon-node:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    depends_on:
      - bootnode
      - execution-node
    image: lighthouse-interop
    pull_policy: never
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_1", "http://execution-node:8551"]
    environment:
      - P2P_PORT=9000
    ports:
      - "5052:5052"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - lighthouse_data:/data
      - config_data:/config_data
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret

  lighthouse-beacon-node-follower:
    depends_on:
      - execution-node-2
      - bootnode
      - lighthouse-beacon-node
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_2", "http://execution-node-2:8551"]
    environment:
      - P2P_PORT=9001
    ports:
      - "5053:5052"
      - "8001:8000"
      - "9001:9001"
    volumes:
      - lighthouse_data:/data
      - config_data:/config_data
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret

  lighthouse-validator-node:
    image: lighthouse-interop
    pull_policy: never
    depends_on:
      - lighthouse-beacon-node
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    entrypoint: ['run_validator.sh', 'http://lighthouse-beacon-node:8000']
    volumes:
      - lighthouse_data:/data
      - config_data:/config_data
      - type: bind
        source: ./lighthouse/run_validator.sh
        target: /usr/local/bin/run_validator.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
