version: '3.4'

volumes:
  geth_data:
  geth_data2:
  beacon_node_data:
  beacon_node_follower_data:
  lighthouse_shared_config:
  lighthouse_data:


services:
  build-shared-states:
    build:
      context: ./
      dockerfile: ./prysm/Dockerfile.prysm
    entrypoint: [ "/shared/setup.sh" ]
    volumes:
      - ./shared:/shared

  execution-node:
    depends_on:
      - prysm-beacon-node
    image: inphi/geth:eip4844-devnet4
    ports:
      - '8545:8545'
      - '8551:8551'
    entrypoint: [ "geth.sh" ]
    volumes:
      - ./shared:/shared
      - 'geth_data:/db'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  execution-node-2:
    depends_on:
      - execution-node
      - prysm-beacon-node-follower
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8546:8545'
      - '8552:8551'
    entrypoint: [ "geth.sh" ]
    volumes:
      - ./shared:/shared
      - 'geth_data2:/db'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  prysm-beacon-node:
    depends_on:
      - jaeger-tracing
    build:
      context: ./
      dockerfile: ./prysm/Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node:8551
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
      P2P_TCP_PORT: 13000
    entrypoint:
      [
        'run_beacon_node.sh',
        '--min-sync-peers=0',
        '--bootstrap-node='
      ]
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - './shared:/shared'
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/prysm-priv-key
        target: /etc/prysm-priv-key

  prysm-beacon-node-follower:
    depends_on:
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./
      dockerfile: ./prysm/Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8551
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node-follower
      BEACON_NODE_RPC: http://prysm-beacon-node:3500
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
      P2P_TCP_PORT: 13001
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13001'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - './shared:/shared'
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./prysm/prysm-follower-priv-key
        target: /etc/prysm-priv-key

  prysm-validator-node:
    depends_on:
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./
      dockerfile: ./prysm/Dockerfile.prysm
    command: >
      validator 
        --accept-terms-of-use 
        --beacon-rpc-provider prysm-beacon-node:4000 
        --rpc 
        --grpc-gateway-host 0.0.0.0 
        --grpc-gateway-port 7500
        --interop-num-validators=4 
        --interop-start-index=0 
        --force-clear-db 
        --chain-config-file=/shared/chain-config.yml 
        --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b 
        --enable-tracing 
        --tracing-endpoint http://jaeger-tracing:14268/api/traces 
        --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - './shared:/shared'

  lodestar-beacon-node:
    depends_on:
      - execution-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      PROCESS_NAME: lodestar-beacon-node
    entrypoint: [ 'run_beacon_node.sh' ]
    ports:
      - '3500:3500'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh

  lodestar-beacon-node-follower:
    depends_on:
      - execution-node-2
      - lodestar-beacon-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      BEACON_NODE_RPC: http://lodestar-beacon-node:3500
      PROCESS_NAME: lodestar-beacon-node-follower
      VERBOSITY: debug
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lodestar/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh

  # TODO: temporary solution for generating genesis, remove this before merge
  lcli-build-genesis:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    entrypoint: [ "generate-genesis.sh" ]
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - "./lighthouse/vars.env:/config/vars.env"
      - type: bind
        source: ./lighthouse/generate-genesis.sh
        target: /usr/local/bin/generate-genesis.sh
      - type: bind
        source: ./lighthouse/genesis.json
        target: /config/genesis.json
      - type: bind
        source: ./lighthouse/generated-genesis.json
        target: /config/generated-genesis.json
      - type: bind
        source: ./lighthouse/generated-config.yaml
        target: /config/generated-config.yaml

  lighthouse-bootnode:
    depends_on:
      - lcli-build-genesis
    image: lighthouse-interop
    pull_policy: never
    command: run_bootnode.sh
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_bootnode.sh
        target: /usr/local/bin/run_bootnode.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env

  lighthouse-beacon-node:
    depends_on:
      - lighthouse-bootnode
      - execution-node
      - lcli-build-genesis
    # build:
    #   context: ./lighthouse
    #   dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    entrypoint:
      [
        "run_beacon_node.sh",
        "-d",
        "debug",
        "/data/node_1",
        "http://execution-node:8551"
      ]
    environment:
      - P2P_PORT=9000
    ports:
      - "5052:5052"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret

  lighthouse-beacon-node-follower:
    depends_on:
      - execution-node-2
      - lighthouse-beacon-node
    # build:
    #   context: ./lighthouse
    #   dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    entrypoint:
      [
        "run_beacon_node.sh",
        "-d",
        "debug",
        "/data/node_2",
        "http://execution-node-2:8551"
      ]
    environment:
      - P2P_PORT=9001
    ports:
      - "5053:5052"
      - "8001:8000"
      - "9001:9001"
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /config/jwtsecret

  lighthouse-validator-node:
    image: lighthouse-interop
    pull_policy: never
    depends_on:
      - lighthouse-beacon-node
    entrypoint:
      [
        'run_validator.sh',
        'http://lighthouse-beacon-node:8000'
      ]
    volumes:
      - lighthouse_data:/data
      - lighthouse_shared_config:/lighthouse_shared_config
      - type: bind
        source: ./lighthouse/run_validator.sh
        target: /usr/local/bin/run_validator.sh
      - type: bind
        source: ./lighthouse/vars.env
        target: /config/vars.env

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
