version: '3.4'

volumes:
  lighthouse_data:
  prysm_data:
  lodestar_data:
  config_data:

x-geth: &geth
  build:
    context: ./geth
    dockerfile: Dockerfile.geth
  entrypoint: geth.sh
  healthcheck:
    test: ["CMD", "curl", "--fail", "localhost:8545"]
    interval: 2s
    timeout: 2s
    retries: 20
    start_period: 1s
  volumes:
    - 'config_data:/config_data'
    - type: bind
      source: ./geth/geth.sh
      target: /usr/local/bin/geth.sh

x-prysm-beacon-node-env: &prysm-bn-env
  TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
  PROCESS_NAME: beacon-node
  VERBOSITY: debug
  P2P_PRIV_KEY: /etc/prysm-priv-key
  P2P_TCP_PORT: 13000
  MIN_SYNC_PEERS: 0

x-prysm-beacon-node: &prysm-bn
  depends_on:
    bootnode:
      condition: service_started
    jaeger-tracing:
      condition: service_started
  build:
    context: ./prysm
    dockerfile: Dockerfile.prysm
  healthcheck:
    test: ["CMD", "curl", "--fail", "localhost:3500/eth/v1/node/health"]
    interval: 2s
    timeout: 2s
    retries: 20
    start_period: 1s
  entrypoint: run_beacon_node.sh
  volumes:
    - 'config_data:/config_data'
    - type: bind
      source: ./prysm/run_beacon_node.sh
      target: /usr/local/bin/run_beacon_node.sh
    - type: bind
      source: ./prysm/prysm-priv-key
      target: /etc/prysm-priv-key

x-lighthouse-beacon-node: &lighthouse-bn
  build:
    context: ./lighthouse
    dockerfile: Dockerfile.lighthouse
  image: lighthouse-interop
  pull_policy: never
  entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_1", "http://geth-1:8551"]
  environment:
    - P2P_PORT=9000
  ports:
    - "5052:5052"
    - "8000:8000"
    - "9000:9000"
  volumes:
    - lighthouse_data:/data
    - config_data:/config_data
    - type: bind
      source: ./lighthouse/run_beacon_node.sh
      target: /usr/local/bin/run_beacon_node.sh
    - type: bind
      source: ./shared/trusted_setup.txt
      target: /config/trusted_setup.txt
    - type: bind
      source: ./shared/jwtsecret
      target: /config/jwtsecret


services:
  genesis-generator:
    image: inphi/ethereum-genesis-generator:eip4844-alpha
    entrypoint: run_genesis_generator.sh
    volumes:
      - ./shared/run_genesis_generator.sh:/usr/local/bin/run_genesis_generator.sh
      - ./shared/genesis-generator-configs:/config
      - ./shared/generated-configs:/gen-configs
      - lighthouse_data:/lighthouse_data
      - prysm_data:/prysm_data
      - lodestar_data:/lodestar_data
      - config_data:/data

  geth-1:
    <<: *geth
    ports:
      - '8545:8545'
      - '8551:8551'

  geth-2:
    <<: *geth
    ports:
      - '8546:8545'
      - '8552:8551'

  geth-3:
    <<: *geth
    ports:
      - '8547:8545'
      - '8553:8551'

  nethermind:
    image: nethermindeth/nethermind:eip-4844-v4
    ports:
      - '10545:8545'
    entrypoint: 'nethermind.sh'
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8545"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 1s
    volumes:
      - 'config_data:/config_data'
      - type: bind
        source: ./nethermind/nethermind.sh
        target: /usr/local/bin/nethermind.sh

  # TODO: move bootnode to genesis-generator
  bootnode:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    pull_policy: never
    command: run_bootnode.sh
    volumes:
      - lighthouse_data:/data
      - config_data:/config_data
      - ./shared/genesis-generator-configs/values.env:/config/values.env
      - type: bind
        source: ./lighthouse/run_bootnode.sh
        target: /usr/local/bin/run_bootnode.sh

  prysm-beacon-node:
    <<: *prysm-bn
    depends_on:
      #nethermind:
      #condition: service_started
      geth-1:
        condition: service_healthy
      bootnode:
        condition: service_started
      jaeger-tracing:
        condition: service_started
    environment:
      <<: *prysm-bn-env
      EXECUTION_NODE_URL: http://geth-1:8551
      PROCESS_NAME: beacon-node
      MIN_SYNC_PEERS: 0
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'

  prysm-beacon-node-follower:
    <<: *prysm-bn
    depends_on:
      geth-2:
        condition: service_healthy
      prysm-beacon-node:
        condition: service_started
      bootnode:
        condition: service_started
      jaeger-tracing:
        condition: service_started
    environment:
      <<: *prysm-bn-env
      EXECUTION_NODE_URL: http://geth-2:8551
      PROCESS_NAME: beacon-node-follower
      P2P_TCP_PORT: 13001
      MIN_SYNC_PEERS: 1
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13001'

  prysm-validator-node:
    depends_on:
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --force-clear-db
      --chain-config-file=/config_data/custom_config_data/config.yaml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --wallet-password-file=/prysm_data/wallet_pass.txt
      --wallet-dir=/prysm_data/wallet
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - 'config_data:/config_data'
      - 'prysm_data:/prysm_data'

  lodestar-beacon-node:
    depends_on:
      bootnode:
        condition: service_started
      geth-3:
        condition: service_healthy
    image: g11tech/lodestar:4844-jan23
    environment:
      EXECUTION_NODE_URL: http://geth-3:8551
    entrypoint: ['run_beacon_node.sh']
    ports:
      - '3600:3500'
      - '14000:13000'
    volumes:
      - 'config_data:/config_data'
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh

  lodestar-validator-node:
    depends_on:
      - lodestar-beacon-node
    image: g11tech/lodestar:4844-jan23
    command: >
      node ./packages/cli/bin/lodestar validator
      --paramsFile /config_data/custom_config_data/config.yaml
      --force
      --dataDir /chaindata/validator
      --keystoresDir /lodestar_data/keystores
      --secretsDir /lodestar_data/secrets
      --server http://lodestar-beacon-node:3500
      --suggestedFeeRecipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
    volumes:
      - 'config_data:/config_data'
      - 'lodestar_data:/lodestar_data'

  lighthouse-beacon-node:
    <<: *lighthouse-bn
    depends_on:
      - bootnode
      - geth-1
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_1", "http://geth-1:8551"]
    environment:
      - P2P_PORT=9000
    ports:
      - "5052:5052"
      - "8000:8000"
      - "9000:9000"

  lighthouse-beacon-node-follower:
    <<: *lighthouse-bn
    depends_on:
      - geth-2
      - bootnode
      - lighthouse-beacon-node
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_2", "http://geth-2:8551"]
    environment:
      - P2P_PORT=9001
    ports:
      - "5053:5052"
      - "8001:8000"
      - "9001:9001"

  lighthouse-validator-node:
    image: lighthouse-interop
    pull_policy: never
    depends_on:
      - lighthouse-beacon-node
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    command: >
      lighthouse
      --debug-level info
      vc
      --validators-dir /data/validators
      --secrets-dir /data/secrets
      --testnet-dir /config_data/custom_config_data
      --init-slashing-protection
      --beacon-nodes http://lighthouse-beacon-node:8000
      --suggested-fee-recipient 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
    volumes:
      - lighthouse_data:/data
      - config_data:/config_data

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
