CONFIG_NAME: "local"
ALTAIR_FORK_EPOCH: 1
BELLATRIX_FORK_EPOCH: 2
EIP4844_FORK_EPOCH: 3 # ensure this happens before shardingForkBlock in execution
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 3
TERMINAL_TOTAL_DIFFICULTY: 2

# avoid collisions with mainnet/eip4844 config versioning
GENESIS_FORK_VERSION: 0x00000ffe
ALTAIR_FORK_VERSION: 0x01000ffe
BELLATRIX_FORK_VERSION: 0x02000ffe
EIP4844_FORK_VERSION: 0x03000ffe

DOMAIN_BLOBS_SIDECAR: 0x0a000000
