CONFIG_NAME: 'local'

ALTAIR_FORK_EPOCH: 1
BELLATRIX_FORK_EPOCH: 2
CAPELLA_FORK_EPOCH: 3
EIP4844_FORK_EPOCH: 4 # ensure this happens at exactly shardingForkBlock in execution
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 3
TERMINAL_TOTAL_DIFFICULTY: 2

# avoid collisions with mainnet/eip4844 config versioning
GENESIS_FORK_VERSION: 0x00000ffe
ALTAIR_FORK_VERSION: 0x01000ffe
BELLATRIX_FORK_VERSION: 0x02000ffe
EIP4844_FORK_VERSION: 0x03000ffe

DOMAIN_BLOBS_SIDECAR: 0x0a000000

# All missing values below (except for DEPOSIT_CONTRACT_ADDRESS) copied from mainnet

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 16384
# Dec 1, 2020, 12pm UTC
MIN_GENESIS_TIME: 1606824000
# 604800 seconds (7 days)
GENESIS_DELAY: 604800

# Time parameters
# ---------------------------------------------------------------
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 2048

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
# Ethereum PoW Mainnet
DEPOSIT_CHAIN_ID: 1
DEPOSIT_NETWORK_ID: 1
DEPOSIT_CONTRACT_ADDRESS: 0x8A04d14125D0FDCDc742F4A05C051De07232EDa4
