PRESET_BASE: 'interop'
CONFIG_NAME: 'interop'

ALTAIR_FORK_EPOCH: 1
BELLATRIX_FORK_EPOCH: 2
CAPELLA_FORK_EPOCH: 3
EIP4844_FORK_EPOCH: 4

SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 6
TERMINAL_TOTAL_DIFFICULTY: 2
MAX_WITHDRAWALS_PER_PAYLOAD: 4

# avoid collisions with mainnet/eip4844 config versioning
GENESIS_FORK_VERSION: 0x20000089
ALTAIR_FORK_VERSION: 0x20000090
BELLATRIX_FORK_VERSION: 0x20000091
CAPELLA_FORK_VERSION: 0x20000092
EIP4844_FORK_VERSION: 0x20000093

# DOMAIN_BLOBS_SIDECAR: 0x0a000000

# Deposit contract
# ---------------------------------------------------------------
# Ethereum PoW Mainnet
DEPOSIT_CHAIN_ID: 1
DEPOSIT_NETWORK_ID: 4242
DEPOSIT_CONTRACT_ADDRESS: 0x8A04d14125D0FDCDc742F4A05C051De07232EDa4
