FROM golang:1.18

COPY ./prysm/prysm/go.mod ./prysm/prysm/go.sum /prysm/
WORKDIR /prysm
RUN go mod download


COPY ./prysm/prysm /prysm/.
WORKDIR /prysm
RUN go build -o /usr/local/bin -buildvcs=false ./cmd/prysmctl

COPY ./shared /shared
WORKDIR /shared
RUN ./setup.sh
